[package]
name = "pacbot-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array-init = "2.1.0"
byteorder = "1.5.0"
rand = "0.8.5"
serde = { version = "1.0.193", features = ["derive", "rc"] }
